import type { GameEvent } from '../../engine/types';

/**
 * The food truck's cards.
 *
 * These share their CONCEPTS with the lemonade stand's — competition, word of
 * mouth, service recovery, shrinkage, insurance — because those are the
 * curriculum. Nothing else is shared. A card written to fit both businesses fits
 * neither, which is how a truck owner ended up being thanked for the lemonade
 * and offered a free cup.
 *
 * Money here is scaled to a truck: it turns over a couple of thousand in a good
 * week, so a $9 problem is not a problem. Roughly ten times the stand.
 */
export const TRUCK_EVENTS: GameEvent[] = [
  {
    id: 'truck-heat',
    pool: 'truck',
    character: 'The Forecast',
    emoji: '🥵',
    title: 'Heat Wave',
    line: 'Ninety-five and climbing. Nobody wants to cook tonight.',
    weight: 10,
    seasons: ['summer'],
    weathers: ['hot', 'sunny'],
    concept: 'Demand shocks',
    choices: [
      {
        id: 'raise',
        label: 'Raise prices today',
        priceMod: 1.25,
        reputation: -0.15,
        result: 'Surge pricing. Some grumble, and the line stays long.',
      },
      {
        id: 'normal',
        label: 'Hold the price',
        reputation: 0.15,
        result: 'Same price all week, in that heat. People remember it.',
      },
    ],
  },
  {
    id: 'truck-cold',
    pool: 'truck',
    character: 'The Forecast',
    emoji: '🥶',
    title: 'Cold Snap',
    line: 'Nobody is eating outside in this. Not for long, anyway.',
    weight: 8,
    seasons: ['fall', 'winter', 'spring'],
    weathers: ['cold'],
    concept: 'Seasonality',
    choices: [
      {
        id: 'soup',
        label: 'Put soup on',
        cash: -60,
        demandMod: 1.6,
        result: 'Hot soup in the cold. It carries the whole week.',
      },
      {
        id: 'ride',
        label: 'Ride it out',
        result: 'A slow, cold week. At least it cost you nothing extra.',
      },
    ],
  },
  {
    id: 'truck-fryer',
    pool: 'truck',
    character: 'The Fryer',
    emoji: '🍳',
    title: 'The Fryer Quits',
    line: 'Halfway through service the oil never comes back up.',
    weight: 8,
    breakdown: true,
    concept: 'Capital expenditure vs deferred maintenance',
    choices: [
      {
        id: 'fix',
        label: 'Buy a new fryer',
        cash: -450,
        equipment: 250,
        result: 'A real commercial unit. Expensive, and it is yours.',
      },
      {
        id: 'tape',
        label: 'Nurse it along',
        cash: -20,
        equipment: -180,
        demandMod: 0.8,
        reputation: -0.1,
        result: 'It limps on, and it is worth less than it was.',
      },
    ],
  },
  {
    id: 'truck-supplier',
    pool: 'truck',
    character: 'Your Supplier',
    emoji: '🚛',
    title: 'Beef Prices Jump',
    line: 'Wholesale went up again. Everyone is passing it on.',
    weight: 8,
    concept: 'Variable cost changes',
    choices: [
      {
        id: 'absorb',
        label: 'Eat the cost',
        unitCostMod: 1.35,
        result: 'Every plate costs more to put out this week.',
      },
      {
        id: 'cheap',
        label: 'Buy the cheaper cut',
        unitCostMod: 1.05,
        demandMod: 0.85,
        reputation: -0.15,
        result: 'Cheaper to make. Your regulars notice immediately.',
      },
    ],
  },
  {
    id: 'truck-parking',
    pool: 'truck',
    character: 'Parking Officer',
    emoji: '🚨',
    title: 'You Cannot Park Here',
    line: 'This block needs a vendor permit. Rules are rules.',
    weight: 6,
    concept: 'Regulatory and fixed costs',
    choices: [
      {
        id: 'pay',
        label: 'Buy the permit',
        cash: -220,
        reputation: 0.1,
        result: 'Paid and legal. You can park here all season now.',
      },
      {
        id: 'move',
        label: 'Find a side street',
        demandMod: 0.7,
        result: 'No fee, and a lot fewer people walking past.',
      },
    ],
  },
  {
    id: 'truck-rival-opens',
    pool: 'truck',
    character: 'The Competition',
    emoji: '😼',
    title: 'A Rival Pulls In',
    line: 'Another truck pulled in twenty feet away. Same menu.',
    weight: 8,
    concept: 'Competition',
    choices: [
      {
        id: 'cut',
        label: 'Undercut them',
        // A price fight has to actually move the PRICE. As a bare demandMod it
        // was free customers with nothing given up — not a price fight, a gift.
        // The demand curve turns the cut into extra plates by itself.
        priceMod: 0.85,
        result: 'You take the price fight. More plates, less on each one.',
      },
      {
        id: 'combo',
        label: 'Add a combo deal',
        cash: -90,
        demandMod: 1.25,
        reputation: 0.2,
        result: 'A combo beats a menu. Your line is the longer one.',
      },
      {
        id: 'ignore',
        label: 'Let them have it',
        demandMod: 0.78,
        result: 'Some of your lunch regulars wander over.',
      },
    ],
  },
  {
    id: 'truck-rival-quits',
    pool: 'truck',
    character: 'The Competition',
    emoji: '🫠',
    title: 'They Are Selling Up',
    line: 'I am done. Want my griddle before it goes online?',
    weight: 5,
    concept: 'Windfalls',
    choices: [
      {
        id: 'take',
        label: 'Just take their customers',
        demandMod: 1.4,
        result: 'Their whole lunch crowd is yours now, and it cost you nothing.',
      },
      {
        id: 'buy',
        label: 'Buy the griddle too',
        cash: -320,
        equipment: 320,
        capacity: 60,
        demandMod: 1.4,
        result: 'Their crowd AND a second griddle. More out the window every week from now on.',
      },
    ],
  },
  {
    id: 'truck-catering',
    pool: 'truck',
    character: 'Office Manager',
    emoji: '📣',
    title: 'Feed Our Whole Floor',
    line: 'Sixty lunches, Thursday, one invoice. Can you do it?',
    weight: 8,
    concept: 'Capacity and promises',
    choices: [
      {
        id: 'yes',
        label: 'Take the booking',
        cash: 620,
        inventory: -60,
        reputation: 0.25,
        result: 'Delivered on time. The whole building knows your name.',
      },
      {
        id: 'no',
        label: 'Too big for us',
        reputation: -0.05,
        result: 'You pass on it. Safer, and no boost.',
      },
    ],
  },
  {
    id: 'truck-pallet',
    pool: 'truck',
    character: 'Your Supplier',
    emoji: '📦',
    title: 'Pallet Price',
    line: 'Take the whole pallet today and I will cut you a deal.',
    weight: 7,
    concept: 'Economies of scale',
    choices: [
      {
        id: 'buy',
        label: 'Take the pallet',
        cash: -240,
        inventory: 130,
        result: 'A whole pallet, well under the usual price.',
      },
      { id: 'skip', label: 'Not this week', result: 'You keep the cash. No harm done.' },
    ],
  },
  {
    id: 'truck-blogger',
    pool: 'truck',
    character: 'Food Blogger',
    emoji: '⭐',
    title: 'Best In The City',
    line: 'I put you top of my street food list this morning.',
    weight: 8,
    minOpenWeeks: 4,
    concept: 'Word of mouth',
    choices: [
      {
        id: 'thanks',
        label: 'Say thank you',
        reputation: 0.3,
        demandMod: 1.15,
        result: 'The post spreads. New faces all week.',
      },
      {
        id: 'free',
        label: 'Comp their meal',
        // The meal leaves the truck and that is the whole cost — you never had
        // the money to lose. Charging cash on top billed the same meal twice.
        inventory: -1,
        reputation: 0.45,
        demandMod: 1.2,
        result: 'They write it up again. Cheapest advertising you will ever buy.',
      },
    ],
  },
  {
    id: 'truck-harsh',
    pool: 'truck',
    character: 'Angry Customer',
    emoji: '😠',
    title: 'Cold And Slow',
    line: 'Twenty minutes in line and it came out cold!',
    weight: 6,
    concept: 'Service recovery',
    choices: [
      {
        id: 'apologize',
        label: 'Refund and apologize',
        // One meal handed back, at whatever you are charging for one.
        cashUnits: -1,
        reputation: 0.15,
        result: 'Handled right. They came back the next week.',
      },
      {
        id: 'ignore',
        label: 'Leave it',
        reputation: -0.12,
        result: 'The review sits there. A few people read it.',
      },
      {
        id: 'argue',
        label: 'Reply angrily',
        // A public row draws a crowd. That is exactly why people pick it, and
        // exactly why it is a trap. With no upside at all it was not a trap —
        // it was a button with no reason on earth to press it.
        demandMod: 1.12,
        reputation: -0.5,
        result: 'Everyone reads it. Nobody comes out of it looking good.',
      },
    ],
  },
  {
    id: 'truck-portion',
    pool: 'truck',
    character: 'Regular Customer',
    emoji: '🍽️',
    title: 'Smaller Plates',
    line: 'Portions have shrunk. Same price though, I notice.',
    weight: 6,
    concept: 'Quality perception',
    choices: [
      {
        id: 'remake',
        label: 'Put the portion back',
        cash: -40,
        unitCostMod: 1.1,
        reputation: 0.2,
        result: 'Plates come out full again. Regulars notice that too.',
      },
      {
        id: 'ignore',
        label: 'Leave it',
        reputation: -0.12,
        result: 'One review, left alone. It nags at your rating.',
      },
      {
        id: 'blame',
        label: 'Blame the supplier',
        // They do credit you for the short cases. Money for standing is a real
        // trade and a real lesson. Losing standing for nothing was neither.
        cash: 45,
        reputation: -0.3,
        result: 'They credit you for the short cases. It still looks bad.',
      },
    ],
  },
  {
    id: 'truck-price-review',
    pool: 'truck',
    character: 'Passerby',
    emoji: '💰',
    title: 'Too Expensive',
    line: 'Nine dollars? Out of a truck? You are dreaming.',
    weight: 6,
    concept: 'Price perception',
    choices: [
      {
        id: 'explain',
        label: 'Explain your costs',
        // Said at the window, to somebody with a line waiting behind them.
        capacityMod: 0.97,
        reputation: 0.12,
        result: 'You walk them through the invoice. They get it.',
      },
      {
        id: 'ignore',
        label: 'Leave it',
        reputation: -0.12,
        result: 'You say nothing. The comment stays up.',
      },
      {
        id: 'discount',
        label: 'Knock a dollar off',
        cash: -55,
        reputation: 0.2,
        demandMod: 0.95,
        result: 'They leave happy. Word gets around that you haggle.',
      },
    ],
  },
  {
    id: 'truck-rude',
    pool: 'truck',
    character: 'Regular Customer',
    emoji: '🙍',
    title: 'Nobody Looked Up',
    line: 'Whoever was on the window barely looked at me.',
    weight: 6,
    minStage: 2,
    requires: 'hasEmployee',
    concept: 'Managing people',
    choices: [
      {
        id: 'talk',
        label: 'Talk to them',
        // The conversation happens in the middle of service, so it costs some
        // service. Free reputation made leaving it alone a choice nobody would
        // ever take, which is the same fault as the inspection card.
        capacityMod: 0.95,
        reputation: 0.18,
        result: 'A quiet talk mid-shift. The window is friendlier all week.',
      },
      {
        id: 'ignore',
        label: 'Leave it',
        reputation: -0.12,
        result: 'Nothing changes, because nothing was said.',
      },
    ],
  },
  {
    id: 'truck-grease',
    pool: 'truck',
    character: 'Passerby',
    emoji: '🧽',
    title: 'Grease On The Window',
    line: 'There is grease running down the side of your window.',
    weight: 6,
    concept: 'Presentation',
    choices: [
      {
        id: 'clean',
        label: 'Scrub it down',
        cash: -45,
        reputation: 0.2,
        result: 'An hour with a bucket. The truck looks sharp again.',
      },
      {
        id: 'ignore',
        label: 'Leave it',
        reputation: -0.12,
        result: 'It stays greasy. People do notice.',
      },
    ],
  },
  {
    id: 'truck-roadworks',
    pool: 'truck',
    character: 'Road Crew',
    emoji: '🚧',
    title: 'They Dug Up The Street',
    line: 'Resurfacing all week. Nobody can reach that curb.',
    weight: 6,
    concept: 'Location risk',
    choices: [
      {
        id: 'stay',
        label: 'Stay put anyway',
        demandMod: 0.55,
        result: 'You sit behind the barriers and take what you can get.',
      },
      {
        id: 'move',
        label: 'Drive somewhere else',
        cash: -35,
        demandMod: 0.9,
        result: 'A tank of gas and a new spot. Mostly fine.',
      },
    ],
  },
  {
    id: 'truck-charity',
    pool: 'truck',
    character: 'Fire Station',
    emoji: '🚒',
    title: 'Feed The Fundraiser',
    line: 'Would you donate lunch for the benefit on Saturday?',
    weight: 6,
    concept: 'Reputation vs revenue',
    choices: [
      {
        id: 'give',
        label: 'Donate the food',
        cash: -250,
        reputation: 0.5,
        result: 'It costs you a Saturday. The whole neighborhood hears about it.',
      },
      {
        id: 'decline',
        label: 'Not this time',
        result: 'You keep the money. Nobody holds it against you.',
      },
    ],
  },
  {
    id: 'truck-sick',
    pool: 'truck',
    character: 'Your Cook',
    emoji: '🤒',
    title: 'Out Sick',
    line: 'I cannot come in. I am not going near food like this.',
    weight: 7,
    minStage: 2,
    requires: 'hasEmployee',
    concept: 'Payroll and coverage',
    choices: [
      {
        id: 'paid',
        label: 'Rest up, still paid',
        reputation: 0.15,
        staffOut: 'paid',
        result: 'The right call, and a very long week on your own.',
      },
      {
        id: 'unpaid',
        label: 'No work, no pay',
        reputation: -0.2,
        staffOut: 'unpaid',
        result: 'You save the wage. They are quiet about it after that.',
      },
    ],
  },
  {
    id: 'truck-register',
    pool: 'truck',
    character: 'The Cash Drawer',
    emoji: '💸',
    title: 'The Money Is Short',
    line: 'Four hundred went through that window. It is not here.',
    weight: 6,
    concept: 'Shrinkage and controls',
    choices: [
      {
        id: 'lockbox',
        label: 'Fit a locking register',
        cash: -340,
        equipment: 120,
        result: 'A locking drawer and a receipt roll. It will not happen twice.',
      },
      {
        id: 'shrug',
        label: 'Chalk it up to experience',
        cash: -220,
        reputation: -0.05,
        result: 'You take the loss and hope.',
      },
    ],
  },
  {
    id: 'truck-insurance',
    pool: 'truck',
    character: 'Insurance Agent',
    emoji: '📑',
    title: 'You Need Liability Coverage',
    line: 'A fryer, a sidewalk, a crowd. Who pays if it goes wrong?',
    weight: 6,
    minOpenWeeks: 2,
    requires: 'notInsured',
    concept: 'Risk and insurance',
    choices: [
      {
        id: 'buy',
        label: 'Take the policy',
        cash: -300,
        reputation: 0.15,
        setsInsured: true,
        result: 'Money for nothing you can see. That is exactly what insurance is — until it is not.',
      },
      {
        id: 'risk',
        label: 'Go without',
        setsInsured: false,
        result: 'You keep the money. You also keep the risk.',
      },
    ],
  },
  {
    id: 'truck-slip-claim',
    pool: 'truck',
    character: 'A Customer',
    emoji: '🩹',
    title: 'Somebody Slipped',
    line: 'Grease on the sidewalk. They went down. Their lawyer called.',
    weight: 9,
    minOpenWeeks: 6,
    requires: 'uninsured',
    concept: 'Risk and insurance',
    choices: [
      {
        id: 'pay',
        label: 'Pay the bill',
        cash: -1200,
        reputation: -0.25,
        result: 'This is what the policy was for. You did not have one.',
      },
      {
        id: 'fight',
        label: 'Refuse to pay',
        cash: -350,
        reputation: -0.7,
        result: 'You saved some money. They told everyone.',
      },
    ],
  },
  {
    id: 'truck-slip-covered',
    pool: 'truck',
    character: 'Your Policy',
    emoji: '📑',
    title: 'Somebody Slipped',
    line: 'Grease on the sidewalk. They went down. You have a policy for this.',
    weight: 6,
    minOpenWeeks: 6,
    requires: 'insured',
    concept: 'Risk and insurance',
    choices: [
      {
        id: 'file',
        label: 'File the claim',
        cash: -80,
        reputation: 0.1,
        result: 'The policy paid. That is what the nothing-this-week was for.',
      },
      {
        id: 'ignore',
        label: 'Handle it myself',
        reputation: -0.4,
        result: 'You had a policy. You did not use it.',
      },
    ],
  },
  {
    id: 'truck-spoiled',
    pool: 'truck',
    character: 'The Cooler',
    emoji: '🤢',
    title: 'It Failed Overnight',
    line: 'It sat at fifty degrees for nine hours. All of it.',
    weight: 7,
    seasons: ['spring', 'summer'],
    breakdown: true,
    concept: 'Inventory risk',
    choices: [
      {
        id: 'dump',
        label: 'Throw it all out',
        inventory: -80,
        result: 'Painful, and nobody got sick. That is the trade-off.',
      },
      {
        id: 'sell',
        label: 'Serve it anyway',
        reputation: -0.7,
        demandMod: 0.85,
        result: 'People find out. They always find out.',
      },
    ],
  },
  {
    id: 'truck-washout',
    pool: 'truck',
    character: 'The Forecast',
    emoji: '⛈️',
    title: 'A Wet Week',
    line: 'Rain all week. Nobody eats standing up in the rain.',
    weight: 7,
    weathers: ['rain', 'cloudy'],
    concept: 'Demand shocks you cannot control',
    choices: [
      {
        id: 'wait',
        label: 'Wait it out',
        result: 'A wet, quiet week. At least it cost you nothing extra.',
      },
      {
        id: 'canopy',
        label: 'Put up a canopy',
        cash: -180,
        demandMod: 1.5,
        result: 'Somewhere dry to wait. People stop instead of hurrying past.',
      },
    ],
  },

  /* ---- The cards only a truck can deal, from spec section 4. ---- */
  {
    id: 'truck-viral',
    pool: 'truck',
    character: 'Your Phone',
    emoji: '📱',
    title: 'You Went Viral',
    line: 'Someone filmed your window. It is everywhere.',
    weight: 8,
    // A used truck opens on week 5 after sitting in a shop. Nobody filmed a
    // window that was not serving. Four open weeks is long enough to be seen.
    minOpenWeeks: 4,
    concept: 'Demand you did not plan for',
    choices: [
      {
        id: 'ride',
        label: 'Ride the wave',
        demandMod: 1.7,
        reputation: 0.15,
        result: 'A line around the block. Hope you prepped enough.',
      },
      {
        id: 'staff',
        label: 'Call in extra hands',
        cash: -140,
        demandMod: 1.7,
        capacityMod: 1.5,
        reputation: 0.25,
        result: 'You paid for the help and served nearly all of them.',
      },
    ],
  },
  {
    id: 'truck-engine',
    pool: 'truck',
    character: 'The Engine',
    emoji: '🔩',
    title: 'The Engine Blows',
    line: 'It got you there. It is not getting you home.',
    weight: 7,
    breakdown: true,
    concept: 'A vehicle is an asset that fails',
    choices: [
      {
        id: 'proper',
        label: 'Fix it right',
        cash: -900,
        equipment: 400,
        result: 'Fixed right. Expensive, and it holds.',
      },
      {
        id: 'bodge',
        label: 'Patch it for now',
        cash: -180,
        equipment: -350,
        demandMod: 0.85,
        result: 'Running again, sort of. It is worth less than it was.',
      },
      {
        id: 'skip',
        label: 'Do not move this week',
        demandMod: 0.45,
        locksLocation: true,
        result: 'You stay put and take whoever walks past.',
      },
    ],
  },
  {
    id: 'truck-slot',
    pool: 'truck',
    character: 'The Organizer',
    emoji: '🎟️',
    title: 'The Good Slot Is Up',
    line: 'Main gate spot, Saturday. Highest bidder takes it.',
    weight: 7,
    // Only at the seasonal destination. Bidding for a spot you are not
    // attending is not a decision, it is a non sequitur.
    locations: [
      'farmers-market',
      'ballpark',
      'county-fair',
      'lake-resort',
      'pumpkin-patch',
      'haunted-house',
      'winter-market',
      'ice-rink',
    ],
    concept: 'Bidding for a spot with no guarantee',
    choices: [
      {
        id: 'high',
        label: 'Bid high',
        cash: -320,
        demandMod: 1.85,
        reputation: 0.1,
        result: 'The gate is yours. Everyone walks past you first.',
      },
      {
        id: 'low',
        label: 'Bid low',
        cash: -90,
        demandMod: 1.15,
        result: 'You get a corner by the dumpsters. Some people find you.',
      },
      { id: 'pass', label: 'Skip it', result: 'You keep the money and the spot you already have.' },
    ],
  },
  {
    id: 'truck-permit',
    pool: 'truck',
    character: 'Health Inspector',
    emoji: '📋',
    title: 'Surprise Inspection',
    line: 'Your cooler is running warm. I can shut you down today or write it up.',
    weight: 7,
    concept: 'Compliance is a cost of doing business',
    /**
     * This card used to ask whether you had kept a temperature log — $60 if you
     * had, $260 and a reputation hit if you had not. Nobody picks the second
     * one, because it is not a choice: whether the log exists was decided weeks
     * ago, and the card was really a menu with a wrong answer printed on it.
     *
     * A real inspection costs you either way, and in the present tense. Close
     * and fix it and most of the week's trade is gone; stay open and take the
     * write-up and you pay in cash and in your rating. That is the lesson —
     * compliance is bought with time or with money, never with neither.
     */
    choices: [
      {
        id: 'close',
        label: 'Close today and fix it',
        cash: -120,
        demandMod: 0.4,
        reputation: 0.2,
        result: 'Closed by noon, fixed by dark. Most of the week is gone.',
      },
      {
        id: 'writeup',
        label: 'Stay open, take the write-up',
        cash: -260,
        reputation: -0.3,
        result: 'You trade all week and the fine lands with the rating.',
      },
    ],
  },
  {
    id: 'truck-propane',
    pool: 'truck',
    character: 'Gas Supplier',
    emoji: '🔥',
    title: 'Propane Spikes',
    line: 'Gas went up forty percent. Everyone is feeling it.',
    weight: 7,
    concept: 'Input costs you cannot control',
    choices: [
      {
        id: 'absorb',
        label: 'Swallow the cost',
        unitCostMod: 1.3,
        result: 'Every meal costs more to cook this week.',
      },
      {
        id: 'bulk',
        label: 'Buy a month up front',
        cash: -420,
        unitCostMod: 0.92,
        result: 'A lot of money now, and cheaper cooking for a while.',
      },
      {
        id: 'shorten',
        label: 'Cook less, sell out sooner',
        unitCostMod: 1.05,
        capacityMod: 0.75,
        result: 'You run a tighter service. Fewer served, cheaper each.',
      },
    ],
  },
];
